apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
    - name: gl
      context: "golint"
      always_run: true
      optional: false
      source: "golint.yaml"
    - name: pr
      context: "pr"
      always_run: true
      optional: false
      source: "pullrequest.yaml"
    - name: release
  postsubmits:
    - name: release
      context: "release"
      source: "release.yaml"
      branches:
        - ^main$
        - ^master$